### ISSUE TITLE
Unresolved references

### ISSUE THREAD

**Issue by rzwc** [kslides/kslides-template#2]
Hey! New to Kotlin, so sorry if this is a simple question. I'm trying to run your project, trying to run ```main()```. 

Once I run ```./gradlew clean build```, Slides.kt gets highlighted red and I have over a hundred unresolved reference errors. Any idea what the problem might be? I'm thinking it may have to do with Intellij and how I'm setting up the project structure/sdks?

![image](https://github.com/kslides/kslides-template/assets/51135299/dd662ec0-cc40-49d5-9bee-4a6a4d89ddad)

![image](https://github.com/kslides/kslides-template/assets/51135299/165c28ff-b550-4445-a2a0-7d14ab6e3801)

**Comment by rzwc** [comment]
Not sure what happened but I clicked on Analyze Dependencies on the Gradle window and then things started working. There are still red underlines present there though.
![image](https://github.com/kslides/kslides-template/assets/51135299/ec5684de-e4b6-4ae5-ac3d-55f3143197fa)

**Comment by pambrose** [comment]
The red highlighting indicates that the jar cannot be found. If you are in IJ, click on the gradle elephant icon on the upper right and then click on the circular arrows to grab the jars from the maven repo.
